<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
 <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
 <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
 <PackageReference Include="HtmlSanitizer" Version="9.0.892" />
 <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.5" />
 <PackageReference Include="MudBlazor" Version="9.2.0" />
    <PackageReference Include="Spillgebees.Blazor.RichTextEditor" Version="2.2.0" />
  </ItemGroup>

</Project>
