namespace HomeSeeker.Models;

/// <summary>
/// Represents a single scan run for a search profile.
/// </summary>
public class ScanRun
{
    public Guid Id { get; set; }

    /// <summary>
    /// Associated search profile ID.
    /// </summary>
    public Guid SearchProfileId { get; set; }

    /// <summary>
    /// Current status of the scan.
    /// </summary>
    public ScanStatus Status { get; set; } = ScanStatus.Running;

    /// <summary>
    /// When the scan started.
    /// </summary>
    public DateTime StartedAt { get; set; }

    /// <summary>
    /// When the scan completed (or failed).
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Number of listings found.
    /// </summary>
    public int ListingsFoundCount { get; set; }

    /// <summary>
    /// Number of new listings (not seen before).
    /// </summary>
    public int NewListingsCount { get; set; }

    /// <summary>
    /// Number of listings with price drops.
    /// </summary>
    public int PriceDropsCount { get; set; }

    /// <summary>
    /// Number of listings evaluated by AI.
    /// </summary>
    public int EvaluatedCount { get; set; }

    /// <summary>
    /// HTML report generated by AI.
    /// </summary>
    public string? ReportHtml { get; set; }

    /// <summary>
    /// Error message if scan failed.
    /// </summary>
    public string? Error { get; set; }

    // Navigation property
    public SearchProfile? SearchProfile { get; set; }
}

/// <summary>
/// Status of a scan run.
/// </summary>
public enum ScanStatus
{
    Running = 0,
    Completed = 1,
    Failed = 2
}
